# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  inputs:
    script: |
      tar -czf mongodb-${BUILD_BUILDNUMBER}.tar.gz *.js
      curl -v -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file mongodb-${BUILD_BUILDNUMBER}.tar.gz https://172.31.41.54:8081/repository/mongodb-dev/mongodb-${BUILD_BUILDNUMBER}.tar.gz
  displayName: Upload to Nexus
  env:
    NEXUS_PASSWORD: $(NEXUS_PASSWORD)